# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and deploy to Firebase Hosting
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 14.x
      uses: actions/setup-node@v4
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: List directory contents
      run: ls
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install -g firebase-tools
        firebase deploy --only hosting --project comisaria-blockchain
